#!/usr/bin/env bash

update_vsdiff() {
  product="$1"
  type="$2"
  quality="$3"

  if [[ "$product" == "codigo" ]]; then
    TAG="$(curl -sI https://github.com/btwiuse/vscodium/releases/latest | grep location: | rev | cut -d / -f 1 | rev | tr -d '[:space:]')"
    if [[ "$type" == "web" ]]; then
      DOWNLOAD_URL="https://github.com/btwiuse/vscodium/releases/download/$TAG/vscodium-web-$TAG.tar.gz"
      OUTPUT_FILE="codigo_web_$TAG.txt"
    elif [[ "$type" == "reh" ]]; then
      DOWNLOAD_URL="https://github.com/btwiuse/vscodium/releases/download/$TAG/vscodium-reh-linux-x64-$TAG.tar.gz"
      OUTPUT_FILE="codigo_reh_$TAG.txt"
    elif [[ "$type" == "reh-web" ]]; then
      DOWNLOAD_URL="https://github.com/btwiuse/vscodium/releases/download/$TAG/vscodium-reh-web-linux-x64-$TAG.tar.gz"
      OUTPUT_FILE="codigo_reh-web_$TAG.txt"
    else
      echo "Invalid type for codigo: $type"
      return 1
    fi
  elif [[ "$product" == "vscode" ]]; then
    if [[ "$type" == "web" ]]; then
      URL="https://update.code.visualstudio.com/api/update/web-standalone/$quality/latest"
      JSON="$(curl -sL $URL | jq .)"
      NAME="$(jq -r .name <<< "$JSON")"
      DOWNLOAD_URL="$(jq -r .url <<< "$JSON")"
      OUTPUT_FILE="vscode_web_$NAME.txt"
    elif [[ "$type" == "reh" ]]; then
      URL="https://update.code.visualstudio.com/api/update/server-linux-x64/$quality/latest"
      JSON="$(curl -sL $URL | jq .)"
      NAME="$(jq -r .name <<< "$JSON")"
      DOWNLOAD_URL="$(jq -r .url <<< "$JSON")"
      OUTPUT_FILE="vscode_reh_$NAME.txt"
    elif [[ "$type" == "reh-web" ]]; then
      URL="https://update.code.visualstudio.com/api/update/server-linux-x64-web/$quality/latest"
      JSON="$(curl -sL $URL | jq .)"
      NAME="$(jq -r .name <<< "$JSON")"
      DOWNLOAD_URL="$(jq -r .url <<< "$JSON")"
      OUTPUT_FILE="vscode_reh-web_$NAME.txt"
    else
      echo "Invalid type for vscode: $type"
      return 1
    fi
  elif [[ "$product" == "vscodium" ]]; then
    TAG="$(curl -sI https://github.com/VSCodium/vscodium/releases/latest | grep location: | rev | cut -d / -f 1 | rev | tr -d '[:space:]')"
    if [[ "$type" == "web" ]]; then
      DOWNLOAD_URL="https://github.com/VSCodium/vscodium/releases/download/$TAG/VSCodium-linux-x64-$TAG.tar.gz"
      OUTPUT_FILE="vscodium_web_$TAG.txt"
    elif [[ "$type" == "reh" ]]; then
      DOWNLOAD_URL="https://github.com/VSCodium/vscodium/releases/download/$TAG/VSCodium-linux-x64-$TAG.tar.gz"
      OUTPUT_FILE="vscodium_reh_$TAG.txt"
    elif [[ "$type" == "reh-web" ]]; then
      DOWNLOAD_URL="https://github.com/VSCodium/vscodium/releases/download/$TAG/VSCodium-linux-x64-$TAG.tar.gz"
      OUTPUT_FILE="vscodium_reh-web_$TAG.txt"
    else
      echo "Invalid type for vscodium: $type"
      return 1
    fi
  else
    echo "Invalid product: $product"
    return 1
  fi

  echo "$product-$type: $NAME"
  echo "$DOWNLOAD_URL"
  curl -#L "$DOWNLOAD_URL" | tar tz | sed \
    -e '/\/$/d' \
    -e 's|^./||g' \
    -e 's|^vscode-web/||g' \
    -e 's|^vscode-server-linux-x64-web/||g' \
    -e 's|^vscode-server-linux-x64/||g' \
    | env LC_ALL=C sort > "$OUTPUT_FILE"
}

update_vsdiff "$@"
