name: Update vsdiff

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update]
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main

jobs:
  update-vsdiff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main

    - name: Config git user
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Run update script
      run: ./vsdiff

    - name: Commit changes
      run: |
        git commit -am 'Update vsdiff files'

    - name: Push changes
      run: |
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
